name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                  .github
                  src
            - name: Welcome
              run: | 
                echo "Welcome"
                ls -ltra
                cat README.md
            - name: Generate ASCII Artwork
              run: | 
                sudo apt-get install cowsay -y
                cowsay -f dragon "Run" >> dragon.txt
                cat dragon.txt

            # - name: List files
            #   run: ls -a

            # - name: Read file
            #   run: cat README.md