name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                  .github
                  src
            - name: Welcome
              run: echo "Welcome"

            - name: List files
              run: ls -a

            - name: Read file
              run: cat README.md